### ISSUE TITLE
Update to newer Rust nightly

### ISSUE THREAD

**Issue by shiatsumat** [xldenis/creusot#103]
Creusot currently supports `nightly-2021-08-30`, but things change fast in Rust.
It would be nice if Creusot is updated to the newer Rust nightly.
This is particularly because `aarch64-apple-darwin` (which I mainly use recently) is better supported in the latest versions.
It seems that Rustc has undergone some big changes, such as split of the `rustc_mir` crate into `rustc_mir_build`, `rustc_mir_dataflow`, and `rustc_mir_transform`.

**Comment by xldenis** [comment]
oh fun. but yes agreed, I wanted to do the update so I could use `def_path_hash_to_def_id` anyways.

**Comment by shiatsumat** [comment]
Finished by #104.
