### ISSUE TITLE
Support macro invocations in pearlite terms.

### ISSUE THREAD

**Issue by xldenis** [xldenis/creusot#126]
We should allow calls to macros in pearlite terms. Currently this is an error in `pearlite_syn`.

**Comment by xldenis** [comment]
I tried adding this as part of #274, but unfortunately it requires using apis which are not public in syn, much to my chagrin.

**Comment by xldenis** [comment]
We've settled on only allowing whitelisted macros for now (`proof_assert`).

**Comment by jhjourdan** [comment]
The problem being that arbitrary macros could allow writing non-pearlite code in pearlite context.

**Comment by xldenis** [comment]
> The problem being that arbitrary macros could allow writing non-pearlite code in pearlite context.

I don't really consider this a problem we need to defend against. They wouldn't be able to do anything unsound, as the "real" parser happens later on in the compilation anyways.
