### ISSUE TITLE
Make it possible to hide the body of public logic function

### ISSUE THREAD

**Issue by jhjourdan** [xldenis/creusot#127]
@xldenis  proposed to have an `#[opaque]` attribute. That's a possibility, indeed.

Then the default is that the body is public when the function is public, which is good, after all.

When the body of a logic function uses private symbols, what should we do? We should either emit an error or make the function opaque automatically. I guess the less surprising behavior is to emit an error.

(I guess Creusot is already doing something when the spec of a function (logic or program) mentions a private symbol (type, function, trait, ....), isn't it?)

**Comment by xldenis** [comment]
Fixed through the addition of opacity and the `#[open(..)]` annotation.
