### ISSUE TITLE
Improvements to the ergonomics of `Model`

### ISSUE THREAD

**Issue by xldenis** [xldenis/creusot#128]
I wonder if we could improve the ergonomics of `Model` a little, in particular by adding an instance for `& T` which forwards to `T`? 

This could let us transform: 
```rust
#[ensures(result.into() === (@*self).len())]
``` 

into:

```rust
 #[ensures(result.into() === (@self).len())]
```

Which seems a little more readable to me?

**Comment by xldenis** [comment]
We should ensure that calls to `@0` are properly 'erased' like they are for `0.into()`

**Comment by xldenis** [comment]
Huh, you're right... it should just work actually

**Comment by shiatsumat** [comment]
Auto-deref does not work because `@x` is translated to a function call `...::Model::model(x)` instead of a method call `x.model()`.
This is a pretty common phenomenon in Rust.
