### ISSUE TITLE
Add Prusti's benchmarks

### ISSUE THREAD

**Issue by shiatsumat** [xldenis/creusot#146]
It's nice to add a number of Prusti's benchmark programs to directly compare Creusot with Prusti and hopefully show Creusot's superiority in various aspects.
https://github.com/viperproject/prusti-dev/tree/master/prusti-tests/tests/verify/pass/

In particular, Prusti has a few interesting benchmarks inspired by Rosetta code (https://github.com/viperproject/prusti-dev/tree/master/prusti-tests/tests/verify/pass/rosetta), and among them `Knuth_shuffle`, `Knights_tour` and `HeapSort` are fairly large and feature vectors.
Probably we can also give and prove stronger specs to these programs with Creusot.

**Comment by xldenis** [comment]
All these examples have been added, proved and improved.
