### ISSUE TITLE
Non exhaustive `match` statements allowed by Creusot

### ISSUE THREAD

**Issue by sarsko** [xldenis/creusot#211]
The following is allowed by Creusot, even though it will fail compilation:

```rust
pub enum E {
    A,
    B,
    C,
}

struct S(E);

fn ex(s: S) {
    match s.0 {
        E::A => {}
    }
}
```

**Comment by xldenis** [comment]
what. how is this caught by nothing? it should definitely be a typing error, right?

**Comment by xldenis** [comment]
As expected, this will generate an unprovable obligation (which is good), but I still don't understand why `rustc` isn't erroring out before we do anything?
