### ISSUE TITLE
Creusot panic for unknown reaso

### ISSUE THREAD

**Issue by claudemarche** [xldenis/creusot#212]
Creusot panics and asks me to report it, on the code below
```
fn main() {
    let mut door_open = [false; 100];
    for pass in 1..101 {
        let mut door = pass;
        while door <= 100 {
            door_open[door - 1] = !door_open[door - 1];
            door += pass;
        }
    }
    for (i, &is_open) in door_open.iter().enumerate() {
        println!("Door {} is {}.", i + 1, if is_open {"open"} else {"closed"});
    }
}
```

**Comment by xldenis** [comment]
This is surely because the code uses iterators (for loop)

**Comment by claudemarche** [comment]
I'm told to report, I report...
Capturing the panic and printing a proper "unsupported feature" message would be better.

**Comment by xldenis** [comment]
Yes you did well by reporting, I'm just noting the missing feature so I can fix it.

**Comment by xldenis** [comment]
Yes you did well by reporting, I'm just noting the missing feature so I can fix it.

**Comment by xldenis** [comment]
The specific error here has been improved somewhat, identifying the constant in the array initializer as the problem.
