### ISSUE TITLE
Collisions on one letter parameters in `logic` functions

### ISSUE THREAD

**Issue by sarsko** [xldenis/creusot#217]
`logic` functions which expand to create temporaries expand to `let a`, `let b`, `let c` etc., which may collide with one letter parameters in the function and either cause a type error or different semantics than anticipated.

```rust
#[logic]
#[variant(c.len())]
fn ex(c: Seq<Int>, a: Int) -> Int {
    if c.len() == 0 {
        0
    } else {
        ex(c.tail(), a)
    }
}
```
Gives the following error in Why3:
`This expression has type seq.Seq.seq int, but is expected to have type int`

Changing it to:
```rust
#[logic]
#[variant(c.len())]
fn ex(c: Seq<Int>, b: Int) -> Int {
    if c.len() == 0 {
        0
    } else {
        ex(c.tail(), b)
    }
}
```
Gives no error.

This seems to be due to it expanding to the following:
` if Seq.length c = 0 then 0 else let a = Tail0.tail c in ex a b`

As anticipated, the following:
```rust
#[logic]
#[variant(c.len())]
fn ex2(c: Seq<Int>, d: Seq<Int>, b: Int) -> Int {
    if c.len() == 0 {
        0
    } else {
        ex2(c.tail(), d.tail(), b)
    }
}
```
Gives the same error:
` This expression has type seq.Seq.seq int, but is expected to have type int`
due to the expansion:
`if Seq.length c = 0 then 0 else let a = Tail0.tail c in let b = Tail0.tail d in ex2 a b b`

Unsound example:
```rust
#[logic]
#[variant(c.len())]
fn ex3(c: Seq<Int>, a: Seq<Int>) -> Int {
    if c.len() == 0 {
        0
    } else {
        ex3(c.tail(), a)
    }
}
```
Which expands to:
` if Seq.length c = 0 then 0 else let a = Tail0.tail c in ex2 a a`

**Comment by sarsko** [comment]
The check seems to assume lexicographic ordering of parameters:
```rust
#[logic]
#[variant(b.len())]
fn ex2(a: Seq<Int>, b: Seq<Int>) -> Int {
    if b.len() == 0 {
        0
    } else {
        ex2(a, b.tail())
    }
}
```
expands to: `if Seq.length b = 0 then 0 else let b = Tail0.tail b in ex2 a b`

whereas(equivalent, but parameter names swapped):
```rust
#[logic]
#[variant(a.len())]
fn ex2(b: Seq<Int>, a: Seq<Int>) -> Int {
    if a.len() == 0 {
        0
    } else {
        ex2(b, a.tail())
    }
}
```
expands to: `if Seq.length a = 0 then 0 else let b = Tail0.tail a in ex2 b b`

**Comment by xldenis** [comment]
I'll have a fix incoming
