### ISSUE TITLE
Error when translating associated type in type declaration

### ISSUE THREAD

**Issue by xldenis** [xldenis/creusot#223]
Currently, we have an error when translating an associated type in a type declaration:

```rust
struct MyType<T : Trait> {
  field: T::AssocTy,
}
```

This is because all types are gathered into one module at the head of the file, and thus has no clone dependencies.

Obviously, this doesn't scale and types will need to be split up into separate modules. I have no idea how we will be able to handle mutually recursive types in that scenario, but we can deal with that when we get there.

**Comment by xldenis** [comment]
A rather annoying consequence is that it means we will need to clone types and perhaps that all types will also become 'monomorphic' in the same way that functions are.

**Comment by jhjourdan** [comment]
Could we have interface/implementation modules for types too?

Anyway, we should really consider using a different approach, such as the first-order encoding of trait polymorphism that I suggested.

**Comment by xldenis** [comment]
> Anyway, we should really consider using a different approach, such as the first-order encoding of trait polymorphism that I suggested.

Yes, I would very much like to experiment with this encoding. If we can avoid the current cloning approach it would definitely improve the situation.

**Comment by xldenis** [comment]
> Could we have interface/implementation modules for types too?

Yes we could introduce them to handle mutually recursive types.

**Comment by xldenis** [comment]
Duplicate of #213
