### ISSUE TITLE
Implement `Resolve` trait for Vec

### ISSUE THREAD

**Issue by jhjourdan** [xldenis/creusot#224]

**Comment by xldenis** [comment]
It should have the following predicate `forall<i : Int> 0 <= i && i <= (@self).len() ==> (@self)[i].resolve()`

**Comment by jhjourdan** [comment]
Nope. The follwoing:

```
forall<i : Int> 0 <= i && i < (@self).len() ==> (@self)[i].resolve()
```

**Comment by xldenis** [comment]
ah right, once again I am foiled by `<=`. The source of all my troubles.
