### ISSUE TITLE
Using pearlite! in a regular Rust function should probably error

### ISSUE THREAD

**Issue by sarsko** [xldenis/creusot#261]
Not super important, but if one forgets to add `#[logic]`/`#[predicate]` and uses the `pearlite!` macro, Creusot will not complain. I think it would be better if it is checked by Creusot, rather than resulting in a not so helpful Why3 error.

Example:
```rust
extern crate creusot_contracts;
use creusot_contracts::*;
fn some_name() -> bool {
    pearlite!{ 0 === 0 }
}
```
Gives the following error in Why3:
File "../ex.mlcfg", line 45, characters 99-109: unbound program function or variable symbol 'From0.from'

**Comment by xldenis** [comment]
I don't know of an easy way to prevent the `pearlite!` invocation itself, but I think this ties in with #35 #167 etc... I've been doing exploratory work on this front about how to enforce a proper separation even at the Rust level, however, it remains "challenging" :P

**Comment by xldenis** [comment]
I think this is pretty trivial to check in a lint :)

**Comment by xldenis** [comment]
Today, we don't forbid the actual macro, but any call to a logical symbol will raise an error. I'm going to close this for now.
