### ISSUE TITLE
Negating bools in function calls to logic functions results in a Why3 error

### ISSUE THREAD

**Issue by sarsko** [xldenis/creusot#265]
Example:
```rust
#[logic]
fn bool_to_bool(b: bool) -> bool {
    b
}

#[logic]
fn ex(){
    pearlite!{ bool_to_bool(!true) };
}
```

Seems to be a simple lack of parentheses. The example above gets written as(among other things):
```ocaml
module Ex_Ex
  clone Ex_BoolToBool_Interface as BoolToBool0
  function ex () : () =
    let _ = BoolToBool0.bool_to_bool not true in ()
end
```
Which can be fixed by adding parantheses:
```ocaml
module Ex_Ex
  clone Ex_BoolToBool_Interface as BoolToBool0
  function ex () : () =
    let _ = BoolToBool0.bool_to_bool (not true) in ()
end
```
Might be the case for other types as well, though Ints seem to be working as intended

**Comment by xldenis** [comment]
It's a problem of precedence because `not` is actually hardcoded into why3 (its not just a function call). I'll take a look.
