### ISSUE TITLE
Logic functions which does not return anything cannot be `pub` / Lemmas cannot be `pub`

### ISSUE THREAD

**Issue by sarsko** [xldenis/creusot#269]
Not allowed:
```rust
#[logic] 
pub fn lemma_ex() {}
#[predicate] 
pub fn lemma_ex() {}
```
(gives "error: expected `fn`")

Allowed:
```rust
#[logic] 
fn lemma_ex() {}
#[predicate] 
fn lemma_ex() {}
```

Allowed:
```rust
#[logic] 
pub fn lemma_ex() -> bool { true }
#[predicate] 
pub fn lemma_ex() -> bool { true }
```

Means that lemmas either have to be local, or return some value.

**Comment by xldenis** [comment]
What if you do `-> ()`?

**Comment by xldenis** [comment]
I'm rewriting the parser which I believe to be the root cause here anyways. I'll verify that it solves this issue.
