### ISSUE TITLE
Add a `#[pure]` annotation 

### ISSUE THREAD

**Issue by xldenis** [xldenis/creusot#28]
Some functions are pure and could be used from both the logic and the program code. To support these functions we should add an annotation `#[pure]` which verifies this property and makes the symbol available in the logic and program. 
These functions would not have access to purely logical operations like quantifiers or `^`. 

It turns out that `logic!` does most of this already, it emits a `let rec function` which does exactly this in why3 but it also erroneously gives access to logical operations. 
`logic!` should be changed to emit only a `function` declaration and we should add a `#[pure]` annotation which emits the previous `let rec function`.

**Comment by xldenis** [comment]
I meant to open a PR for this but 8537c7ec48b015232692b11fc1b91eadac92e288 fixes the first part of this issue, `logic!` now generates only logical symbols. 

I think that adding a `#[pure]` annotation should wait until I've fixed the issue that is plaging function calls / polymorphism.

**Comment by shiatsumat** [comment]
Is the `#[pure]` function what is introduced as a `hybrid` function in the current `README.md`?

I also wonder if the current `logic!` macro can be updated into an attribute macro like `#[pure]`.
https://doc.rust-lang.org/reference/procedural-macros.html#attribute-macros
