### ISSUE TITLE
apparent automatic generation of loop invariant 

### ISSUE THREAD

**Issue by yannickmoy** [xldenis/creusot#309]
I'm puzzled by the fact that Creusot manages to prove the following code even when I comment out the loop invariants `range_i` and `range_j`, which should be essential. I tried a simple example, and Creusot in that case does not manage to prove the range of the iteration variable unless it is given in the loop invariant. Do you have an explanation?

```
extern crate creusot_contracts;
use creusot_contracts::*;
use creusot_contracts::std::*;

#[predicate]
fn match_at(needle: &Vec<u8>, haystack: &Vec<u8>, pos: Int, len: Int) -> bool {
  pearlite! { len <= (@needle).len()
    && pos <= (@haystack).len() - len
    && forall<i: Int>
        0 <= i && i < len ==> (@needle)[i] === (@haystack)[pos + i]
  }
}

#[requires((@needle).len() >= 1 && (@needle).len() <= (@haystack).len())]
#[ensures(@result == (@haystack).len() || @result < (@haystack).len() - (@needle).len() + 1)]
#[ensures(@result < (@haystack).len() ==>
            (match_at(needle, haystack, @result, (@needle).len())
             && (forall <i: Int> 0 <= i && i < @result ==> ! match_at(needle, haystack, i, (@needle).len()))))]
#[ensures(@result == (@haystack).len() ==> (forall <i: Int> 0 <= i && i < (@haystack).len() ==> ! match_at(needle, haystack, i, (@needle).len())))]
fn search(needle: &Vec<u8>, haystack: &Vec<u8>) -> usize {
   let mut i:usize = 0;
   #[invariant(range_i,@i <= (@haystack).len() - (@needle).len() + 1)]
   #[invariant(no_match,forall<k: Int> 0 <= k && k < @i ==> ! match_at(needle, haystack, k, (@needle).len()))]
   while i < haystack.len() - needle.len() + 1 {
      let mut j:usize = 0;
      #[invariant(range_j,@j <= (@needle).len())]
      #[invariant(partial_match,match_at(needle, haystack, @i, @j))]
      while j < needle.len() {
         if needle[j] != haystack[i + j] {
            break
         }
         j += 1
      };
      if j == needle.len() {
         return i
      };
      i += 1
   };
   return haystack.len()
}
```

**Comment by xldenis** [comment]
I believe it's because `range_i` and `range_j` are just strictly weaker versions of the loop condition. The WP gives us the condition for free in the body and the negation of the condition afterwards. You would be able to replace those invariants with `proof_assert!` and always prove them. 

Which specific sub-goals / post-conditions are you surprised are proven without these invariant?

**Comment by yannickmoy** [comment]
The issue is that, without the loop invariants, the only thing know after the loop is, as you said, the negation of the condition, which does not allow proving that the iteration variable is equal to the upper bound of the range after the loop. This should be needed to prove the correction of this code. To see that, remark that the following assertion is not provable after the inner loop:

```
      proof_assert!(@j <= (@needle).len());
```

while this other assertion is provable:

```
proof_assert!(@j > (@needle).len() ==> match_at(needle, haystack, @i, (@needle).len()));
```

which should make it impossible to prove the preservation of the loop invariant on the outer loop. In fact, the problem seems to come from hypotheses added for checking overflows, as the code is fully proved without the mentioned loop invariants when doing proof of absence of overflows, but not when using `CREUSOT_UNBOUNDED=1` to generate the mlcfg, which is unexpected.

**Comment by xldenis** [comment]
Hmm, looking into this further I notice that `false` has entered the context allowing your proofs to pass. I'll need to investigate this unsoundness further.

**Comment by yannickmoy** [comment]
indeed! I missed that the invariant on `range_j` is exactly the first line of `match_at`. Thanks for the investigation, I'm happy that it was not completely useless.

**Comment by xldenis** [comment]
> any idea why the code is fully proved by default, but not when using CREUSOT_UNBOUNDED=1 ?

When you enable `CREUSOT_UNBOUNDED` all the machine integers becmoe `int`, which notably means they can take on negative values. I would assume that your specs are too weak for that case but if you added `0 <= ZZZ` as appropriate they would pass.
