### ISSUE TITLE
Inconsistencies between `mlcfg` script and `cargo creusot`

### ISSUE THREAD

**Issue by ad-anssi** [xldenis/creusot#316]
Here is a small 'src/lib.rs' with a syntax error in ensures annotation:

```
extern crate creusot_contracts;
use creusot_contracts::ensures;

#[ensures(syntax error)]
fn foo() {}
```

When running `mlcfg` script on it, error is signaled:

```
error: unexpected token
 --> src/lib.rs:4:18
  |
4 | #[ensures(syntax error)]
  |                  ^^^^^

error: aborting due to previous error
```

But when running `cargo creusot` on it, the error seems to be ignored. No error/warning message is output, and mlcfg in which the post-condition has been skipped is generated, thus printing all results as Valid during following Why3 verification. Of course the post-condition does not appear in the results but when verifying larger programs without manual inspection of the Why3 output, this can be a problem.

**Comment by xldenis** [comment]
This is most likely because you are not enabling the `contracts` feature of `creusot-contracts` in your Cargo.toml. I'm not sure what the best way to make this more visible to a user would be..

**Comment by ad-anssi** [comment]
Oh right, my mistake, I forgot about the `contracts` feature!

When I add it and fix the syntax error, I now face another issue that I had during a previous attempt: a lot more specs are generated when using `cargo-creusot` agains `mlcfg` script (.mlcfg file contains 4698 lines vs 77 lines). It seems to be the result of translating the `cargo-contracts` dependency into mlcfg. I don't know how to turn if off for this particular crate and it leads to Why3 errors that stop it to check my actual code:

```
File "./c1.mlcfg", line 3661, characters 80-93:
Not a predicate symbol: log_eq
```

**Comment by xldenis** [comment]
Yes, I should probably, disable the `cargo-creusot` executable, it's broken in a subtle way: when you have dependencies it outputs both crate's code stuck together which why3 won't like to load. I have a hacky Makefile which makes this work here: https://github.com/xldenis/rhb-specs/blob/master/Makefile#L9-L15. The real solution i need to do is just no longer emit code to stdout and always to files then it wouldn't be an issue.

**Comment by xldenis** [comment]
Hi @ad-anssi, I've improved the `cargo creusot` command significantly in the latest master. It should now be much more resilient, it also no longer outputs to STDOUT but instead produces a file in `target/debug` (where the executable would go). 

The way I recommend using it is in combination with the following code in your `Cargo.toml`:

```toml
[dependencies]
creusot-contracts = { path = "../creusot/creusot-contracts", version = "^0" }

[features]
contracts = ["creusot-contracts/contracts"]
```

Then running `cargo creusot --features=contracts` should 'do the trick'.
