### ISSUE TITLE
Regression: current master ( 5ac2d86503240c4ae72a593d334961d1daecc87a ) doesn't check overflows

### ISSUE THREAD

**Issue by safinaskar** [xldenis/creusot#325]
Here is 83467599ad72958665e1011411f6695b6febf401:

```text
user@711b7c30eda5:~$ . "$HOME/.cargo/env"; eval $(opam env)
user@711b7c30eda5:~$ echo 'extern crate creusot_contracts; fn main(){ let mut a = 0; loop { a += 1; } }' > ~/a.rs
user@711b7c30eda5:~$ ~/opt/creusot/mlcfg ~/a.rs > ~/a.mlcfg
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/creusot-rustc -Zno-codegen --extern creusot_contracts=./target/debug/libcreusot_contracts.rlib -Ldependency=./target/debug/deps/ --crate-type=lib /home/user/a.rs`
user@711b7c30eda5:~$ ~/opt/creusot/prove -P z3 ~/a.mlcfg
File /home/user/a.mlcfg:
Goal main'vc.
Prover result is: Timeout (5.00s, 12027041 steps).
```

As you can see, creusot fails to check code, because the code contains overflow.

Now let's take current master ( 5ac2d86503240c4ae72a593d334961d1daecc87a ):

```text
user@c5a78b293fa6:~$ . "$HOME/.cargo/env"; eval $(opam env)
user@c5a78b293fa6:~$ echo 'extern crate creusot_contracts; fn main(){ let mut a = 0; loop { a += 1; } }' > ~/a.rs
user@c5a78b293fa6:~$ ~/opt/creusot/mlcfg ~/a.rs > ~/a.mlcfg
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/creusot-rustc -Zno-codegen --extern creusot_contracts=./target/debug/libcreusot_contracts.rlib -Ldependency=./target/debug/deps/ --crate-type=lib /home/user/a.rs`
user@c5a78b293fa6:~$ ~/opt/creusot/prove -P z3 ~/a.mlcfg
user@c5a78b293fa6:~$ echo $?
0
```

Now `~/opt/creusot/prove` incorrectly silently reports success despite overflow

**Comment by xldenis** [comment]
Hi, thanks for the report @safinaskar, the issue you are having is because I recently changed the behavior of `creusot-rustc` and `cargo-creusot` to not output to STDOUT anymore. 

If you look at your `~` directory you should see a `a-rlib.mlcfg` file which is now generated. 

However, it is true that perhaps `why3` should not silently accept an empty file as input.

**Comment by safinaskar** [comment]
@xldenis . `~/opt/creusot/mlcfg` seems to put output file near the script itself, i. e. to `~/opt/creusot/a-rlib.mlcfg`

**Comment by xldenis** [comment]
Ah yes that makes sense as internally the script changes the directory.
