### ISSUE TITLE
Cannot check bubblesort

### ISSUE THREAD

**Issue by safinaskar** [xldenis/creusot#326]
This is my attempt to write bubblesort (it is possible it is buggy)
```rust
extern crate creusot_contracts;

use creusot_contracts::*;

fn sort(a: &mut [i32]) {
    let mut i = 0;
    #[invariant(foo, i < usize::MAX)]
    while i + 1 < a.len() {
        let mut j = 0;
        while j < a.len() - 1 {
            if a[j] > a[j + 1] {
                let mut sw = a[j];
                a[j] = a[j + 1]; // A
                a[j + 1] = sw; // B
            }
            j += 1;
        }
        i += 1;
    }
}
```

Creusot cannot check this file, it reports timeout. If I comment lines A and B, the file passes. I use master ( 5ac2d86503240c4ae72a593d334961d1daecc87a )

**Comment by xldenis** [comment]
In general to prove a program you should prefer to use the why3 ide (available through the `ide` script ) in the ide you can perform a *split* (S) on the task to get a list of sub goals to prove. You should then be able to get a better understanding of what's missing.

**Comment by safinaskar** [comment]
@xldenis . Here is reduced test case:
```rust
extern crate creusot_contracts;

use creusot_contracts::*;

fn sort(a: &mut [i32]) {
    if a.len() == 0 {
        return;
    }
    while true {
        a[0] = 0;
    }
}
```
Creusot reports timeout, but it should report validity

**Comment by xldenis** [comment]
You'll need need to add an invariant which states that the slice's length doesn't change as currently Creusot's encoding loses that information. Take a look at the gnome sort example for an example of what invariants you need.

However, I am working on some fixes in why3 which should improve the situation.

**Comment by xldenis** [comment]
Closing this as, it isn't a bug in Creusot but feel free to reopen if you have further issues or clarifications. Perhaps I should see if we can turn on GitHub Discussions for non-bug discussions
