### ISSUE TITLE
Why3 error on naming parameters `result`

### ISSUE THREAD

**Issue by sarsko** [xldenis/creusot#361]
Okay obviously contrived and not very important, but I think it is nice to move Why3 errors to Creusot.

```rust
extern crate creusot_contracts;
use creusot_contracts::*;

fn result(result: bool) -> bool {
    result == false
}
```

Causes the following Why3 error:
File "../result-rlib.mlcfg", line 18, characters 30-36: Formal parameters of program functions cannot be named 'result'

**Comment by xldenis** [comment]
huh, i thought I caught that one... I must not be using `Ident::build` somewhere...
