### ISSUE TITLE
creusot::builtins does not work on trait instance functions.

### ISSUE THREAD

**Issue by jhjourdan** [xldenis/creusot#366]

**Comment by xldenis** [comment]
I don't understand what you mean? We use it for `int.rs` in various trait impls.

**Comment by xldenis** [comment]
Closing as this feature works (see `int.rs`).

**Comment by jhjourdan** [comment]
Indeed, this works for `Int`. But for the model for slices, this does not. This is why we are forced to use this trick:

https://github.com/xldenis/creusot/blob/0c31200d01d0c0d2ff7b225919094c446941f1b9/creusot-contracts/src/logic/model.rs#L29

**Comment by xldenis** [comment]
It actually does, though it generates slightly different code (logically).

**Comment by xldenis** [comment]
I'm going to close this as we can actually specify `ensures` even on slices.
