### ISSUE TITLE
Add `#[trusted]` annotation

### ISSUE THREAD

**Issue by xldenis** [xldenis/creusot#37]
A `#[trusted]` annotation would allow us to easily axiomitize libraries like `Vec`, we could declare a type and its signatures, with contracts but skip verification of the unsafe code within by marking them as `#[trusted]`

**Comment by shiatsumat** [comment]
I believe this should be tackled soon.
Any idea in implementing this?

**Comment by xldenis** [comment]
Yes, I think this is the most important feature to do at the moment. I've been cleaning up things related to names, traits etc, but this is the only remaining blocker for `Cell` and `Vec`. 

My rough idea of how this would go:

1. Add the attribute to `creusot_contracts_proc`. 
2. In `logic.rs` update `translate_logic` and  `translate_predicate` to see if that attribute is added, if so emit a declaration not a defintiion. 
3. Same thing in `function.rs` emit a declaration from `translate_function`
