### ISSUE TITLE
Error when user forgets to use `pearlite!`

### ISSUE THREAD

**Issue by xldenis** [xldenis/creusot#380]
We should detect and provide a helpful error when the user forgets to use `pearlite! { .. }` in predicates or logical functions.

see #378

**Comment by jhjourdan** [comment]
Or make it implicit in logic and predicate functions?

**Comment by xldenis** [comment]
We can't since attribute macros need to be valid rust syntax, so there's no way for us to handle `^`, `forall`, `exists` or other logical operators.

**Comment by xldenis** [comment]
We now provide an error message when logical symbols are used outside of `pearlite!` contexts.
