### ISSUE TITLE
Running mlcfg against the exercises does not produce any output

### ISSUE THREAD

**Issue by jmg-duarte** [xldenis/creusot#424]
As stated in the title, running the following line does not produce an MLCFG file
```bash
$ ./mlcfg exercises/01_sum.rs
```

I'm running on `master`

**Comment by sarsko** [comment]
Long time since I have used `./mlcfg` directly, but I believe it either dumps to stdout, or puts the generated file in `/target/debug/BLABLA`

**Comment by sarsko** [comment]
Okay, I just tried the following: `./mlcfg ~/master/sat-mirror/playground/test_creusot.rs` which resulted in the `test_creusot-rlib.mlcfg` file being generated in `.`.

**Comment by xldenis** [comment]
Yea, it behaves basically like `rustc` does, and outputs the file to wherever your current directory is. The `mlcfg` script messes with that so that it always ends up in the root though.

**Comment by jmg-duarte** [comment]
I found it, VSCode was not showing the file 🤦 thanks!
