### ISSUE TITLE
`ide` command is broken

### ISSUE THREAD

**Issue by jmg-duarte** [xldenis/creusot#427]
```bash
$ ./ide 01_sum-rlib.mlcfg  
'ide' is not a Why3 command.

Available commands:
  config
  doc
  execute
  extract
  pp
  prove
  realize
  replay
  session
  shell
  show
  wc
  webserver
```

Why3 version:
```
$ why3 --version 
Why3 platform, version 1.5.0+git
```

**Comment by sarsko** [comment]
I believe you need to install the Why3 IDE by running `opam install why3-ide`

**Comment by jmg-duarte** [comment]
I did, I followed the instructions as specified in the readme

**Comment by xldenis** [comment]
Can you try running `eval $(opam env)` before hand?

**Comment by jmg-duarte** [comment]
The original command (the one with all dependencies) probably failed and ended up not installing the IDE. Forcing a new install worked. Closing now.
