### ISSUE TITLE
Git config symlinks

### ISSUE THREAD

**Issue by dewert99** [xldenis/creusot#428]
As a windows user cloning creusot, I ran into issues where the symlinks were turned plain files containing the path. I eventually figured out that this was caused but having `core.symlinks=false` in my global git config, and I was able to fix this by switching the option to `true` and cloning again. It may be worth mentioning something about this in the README for future users.

**Comment by xldenis** [comment]
I think I'm just going to remove those symlinks, there should only be one anyways.
