### ISSUE TITLE
bigint branch fails when building

### ISSUE THREAD

**Issue by malteafg** [xldenis/creusot#439]
I wanted to experiment with bigints using the bigint branch, however, when building creusot on the bigint branch using the build script I get the following error:
```
Testing tests/should_succeed/bigint.rs ... failure
+  0 ┊ error: extern location for num_bigint does not exist: /Users/xavier/Code/creusot/target/debug/deps/libnum_bigint-5886032f18a4361a.rlib
+  1 ┊  --> bigint.rs:2:1
+  2 ┊   |
+  3 ┊ 2 | extern crate num_bigint;
+  4 ┊   | ^^^^^^^^^^^^^^^^^^^^^^^^
```
I tried looking at Cargo.toml files, but I was unable to figure out how to fix this.

**Comment by xldenis** [comment]
Hi @malteafg, I believe this is just due to the hacky `bigint` test I put in place. I've commented it out and it should now be working.

**Comment by malteafg** [comment]
It works, thanks!
