### ISSUE TITLE
Closure contracts give internal error where referencing arguments

### ISSUE THREAD

**Issue by dewert99** [xldenis/creusot#463]
Example:
```rust
use creusot_contracts::*;
fn test() {
    let c = {
        #[ensures(result == x + 1)]
        |x| x + 1
    };
    let y = c(2);
    proof_assert!(@y == 3)
}
```
gives the error:
```
error[E0425]: cannot find value `x` in this scope
 --> src\fail.rs:4:29
  |
4 |         #[ensures(result == x + 1)]
  |                             ^ not found in this scope

error[creusot]: internal error
```

**Comment by xldenis** [comment]
Thanks for the report @dewert99, I'll take a look this week, if you have time, can you look at some of the closure tests in Creusot to compare with your example?

**Comment by dewert99** [comment]
I looked a bit at the tests in [creusot/tests/should_succeed/closures](https://github.com/xldenis/creusot/blob/master/creusot/tests/should_succeed/closures) and it looks like only `07_mutable_capture.rs` and `08_multiple_calls.rs`  have closures with contracts, and in both cases, the contracts only mention captured variables (not parameters)

**Comment by xldenis** [comment]
> the contracts only mention captured variables (not parameters) 

good catch! I'll fix it this week.
