### ISSUE TITLE
Support Deref in lower_pattern

### ISSUE THREAD

**Issue by shiatsumat** [xldenis/creusot#47]
Currently, `creusot::translation::specification::typing::lower_pattern` supports only limited patterns of [`thir::PatKind`](https://doc.rust-lang.org/stable/nightly-rustc/rustc_middle/thir/enum.PatKind.html),
and especially `Deref` is not supported.

Due to this, for example, we can't write pattern matching over a shared reference to a list like the following.
```rust
logic! {
    fn len(l: &List) -> Int {
        match l {
            Cons(_, l2) => 1 + len(l2),
            Nil => 0,
        }
    }
}
```

**Comment by xldenis** [comment]
I think that we can just go transparently through a deref to a shared list as shared references are erased in logic programs.
