### ISSUE TITLE
How do models work?

### ISSUE THREAD

**Issue by suhr** [xldenis/creusot#478]
I'm trying to do one of exercises in Creusot:

```rust
extern crate creusot_contracts;
use creusot_contracts::*;

// Prove the following:
// 1. If we return Some(i) it is the first index containing `tgt`
// 2. If we return None, then there are no indices containing `tgt`
#[ensures(forall<i:usize> result==Some(i) ==> @i<(@v).len() && (@v)[@i]==*t)]
#[ensures(result==None ==> forall<i:usize> @i<(@v).len() ==> (@v)[@i]!=*t)]
fn search<T: Ord+Model>(v: &Vec<T>, t: &T) -> Option<usize> {
    let mut i: usize = 0;
    #[invariant(ip, @i>=0)]  #[invariant(l, @i<=(@v).len())]
    #[invariant(ne, forall<j:usize> j<i ==> (@v)[@j]!=*t)]
    while i<v.len() {
        if v[i]==*t {proof_assert!((@v)[@i]==*t);  return Some(i)};
        i += 1
    }
    return None;
}
```

CVC5 cannot prove that `(@v)[@i]==*t`. It seams that I don't quite understand how models work. So I would like to know why this does not work and how to fix it.

**Comment by suhr** [comment]
`(@v)[@i] == @t` requires `Model<ModelTy=T>`. But I changed postconditions like so and now it works:

```
#[ensures(forall<i:usize> result==Some(i) ==> @i<(@v).len() && @(@v)[@i]==@t)]
#[ensures(result==None ==> forall<i:usize> @i<(@v).len() ==> (@v)[@i]!=*t)]
```

But there's a weird asymmetry: `==` ensures that models are equal but not the values, while the opposite ensures that values are not equal, but models may be equal.

I probably should read carefully through `creusot-contracts` though.

**Comment by xldenis** [comment]
> while the opposite ensures that values are not equal, but models may be equal.

You should be able to prove that the models are not equal though, as that's implied by the specification of `==`.

**Comment by xldenis** [comment]
> I probably should read carefully through creusot-contracts though.

There's not much to read sadly 🙈, it's mostly just specifications. I recommend looking at the test suite for examples of proofs though.

**Comment by suhr** [comment]
> You should be able to prove that the models are not equal though, as that's implied by the specification of `==`.

Well, for some reason neither CVC5 nor Alt-Ergo can prove `#[ensures(result==None ==> forall<i:usize> @i<(@v).len() ==> @(@v)[@i]!=@t)]`.

**Comment by xldenis** [comment]
The following passes for me:

```
extern crate creusot_contracts;
use creusot_contracts::*;

// Prove the following:
// 1. If we return Some(i) it is the first index containing `tgt`
// 2. If we return None, then there are no indices containing `tgt`
#[ensures(forall<i:usize> result==Some(i) ==> @i<(@v).len() && @(@v)[@i] == @*t)]
#[ensures(result==None ==> forall<i:usize> @i<(@v).len() ==> @(@v)[@i] != @*t)]
fn search<T: Ord + Model>(v: &Vec<T>, t: &T) -> Option<usize> {
    let mut i: usize = 0;
    #[invariant(ip, @i<=(@v).len() )]
    #[invariant(ne, forall<j:usize> j<i ==> @(@v)[@j]!=@*t)]
    while i < v.len() {
        if v[i] == *t {
            return Some(i);
        };
        i += 1
    }
    return None;
}
```

Note: you need to make sure the invariant is properly updated, not just the post-condition.

**Comment by suhr** [comment]
And I indeed forgot to change the loop invariant! Thanks.

PS: `@` is quite verbose — it's used more often then not used. If one could unmodel things insted of modelling them, specifications could be less noisy:

```rust
#[ensures(forall<i:usize> ~result==~Some(~i) ==> i<v.len() && v[i]==t)]
#[ensures(~result==~None ==> forall<i:usize> i<v.len() ==> v[i]!=t)]
fn search<T: Ord+Model>(v: &Vec<T>, t: &T) -> Option<usize> {
    let mut i: usize = 0;
    #[invariant(ip, i>=0)]  #[invariant(l, i<=v.len())]
    #[invariant(ne, forall<j:usize> j<i ==> v[j]!=t)]
    while i<v.len() {
        if v[i]==*t {proof_assert!(v[i]==t);  return Some(i)};
        i += 1
    }
    return None;
}
```

**Comment by xldenis** [comment]
> PS: @ is quite verbose — it's used more often then not used. If one could unmodel things insted of modelling them, specifications could be less noisy:

Indeed, the ergonomics of `Model` leave much to be desired, and your suggestion is quite interesting.. I'll take it into consideration, it's definitely a sore spot I would like to fix
