### ISSUE TITLE
Name `clone` should be escaped

### ISSUE THREAD

**Issue by shiatsumat** [xldenis/creusot#48]
When we use the name `clone` in Rust, Why3 reports a syntax error in the MLCFG output by Creusot.
This is simply because `clone` is a reserved word in MLCFG and Creusot does not escape it.

This happens just by defining a local `clone` function, like:
```rust
fn clone() {}
```

**Comment by xldenis** [comment]
hehe, yea, the code which generates why3 identifiers should escape strings properly. I think that it should be done as part of the constructor of the `why3::name::Ident` type. Provide a `Indent::escaped` function and ensure that it is called in the relevant `From<String>` instance.
