### ISSUE TITLE
"language file for 'Rust' not found in directory"

### ISSUE THREAD

**Issue by Keno** [xldenis/creusot#480]
I was attempting to look at the why3 mlcfg for one of the test cases:
```
./ide creusot/tests/should_succeed/vector/04_binary_search.mlcfg
```
This works fine, except when I navigate the tree on the left in the IDE,
I eventually get the following error:
```
language file for 'Rust' not found in directory /Users/keno/.opam/default/share/why3/lang
```
and the IDE quits. My apologies if I'm doing something dumb here.

**Comment by Keno** [comment]
FWIW, I was able to make progress by grabbing rust.lang from `https://raw.githubusercontent.com/GNOME/gtksourceview/master/data/language-specs/rust.lang` and dumping it into `/Users/keno/.opam/default/share/why3/lang`. It's still not happy about that:
```
(why3:74264): GtkSourceView-WARNING **: 21:45:15.506: Failed to load '/Users/keno/.opam/default/share/why3/lang/rust.lang': invalid context reference 'def:c-like-comment'
```
But at least it's not quitting the IDE anymore.

**Comment by xldenis** [comment]
You need to install `gtk+3` and the associated ocaml packages. I should update the `why3` install instructions to include that:

```
opam install lablgtk3 lablgtk3-sourceview
```

**Comment by xldenis** [comment]
I've updated the installation instructions in the readme to avoid this issue. I hope you are now able to actually load Why3 :)
