### ISSUE TITLE
Specifying a closure with multiple arguments causes why3 error

### ISSUE THREAD

**Issue by dewert99** [xldenis/creusot#487]
Example:
```rust
use creusot_contracts::*;
fn test() {
    let c = {
        #[requires(@x + @y < @u32::MAX)]
        #[ensures(@result == @x + @y)]
        |x: u32, y: u32| x + y
    };
    let z = c(2, 3);
    proof_assert!(@z == 5)
}
```
gives error
```
File "target/debug/my_test-rlib.mlcfg", line 27, characters 99-100:
This term has type (mach.int.UInt32Gen.uint32, mach.int.UInt32Gen.uint32),
but is expected to have type mach.int.UInt32Gen.uint32
```
I think the issue is that internally `precondition` and `postcondition` tuple their arguments, and why3 needs to pattern match and rebind the parameter names.

**Comment by xldenis** [comment]
Thanks again! Can I ask, are you trying to do anything in particular with closures? I'm particularly interested in any use cases you could have.

**Comment by dewert99** [comment]
Thanks for your quick responses.  I've been playing around with a few things including a form of aliasing where one pointer is the primary and other pointers can read/write if you can prove you could have accessed the primary pointer instead (via a closure that is never run), and use this for something like a linked-list with a tail pointer.  I've also been playing a bit with specifying iterator functions.

**Comment by xldenis** [comment]
> I've been playing around with a few things including a form of aliasing where one pointer is the primary and other pointers can read/write if you can prove you could have accessed the primary pointer instead (via a closure that is never run),

Interesting, curious to see how this works! 

>  and use this for something like a linked-list with a tail pointer. I've also been playing a bit with specifying iterator functions.

Any functions in particular? This is something I need to work on more again.

---

Turns out this bug is more annoying to fix than anticipated. The callers of closures expect the arguments to be tupled while the definition of the closure doesn't. It'll take a little more investigation for me to come up with the proper solution here.

**Comment by dewert99** [comment]
> Any functions in particular? This is something I need to work on more again.
I started by implementing fold with a desugared for loop and now am trying to implement for_each with fold which requires the multi-element closure

**Comment by xldenis** [comment]
As a temporary work around you can write your closures with a single tuple argument instead of multiple arguments. I'm going to try tackling the underlying issues in creusot this week.
