### ISSUE TITLE
`let` bindings in contracts

### ISSUE THREAD

**Issue by suhr** [xldenis/creusot#500]
```
error: unexpected token
  --> src/simple.rs:10:38
   |
10 | #[ensures(let l = lmax(@l,(@s).len());  (@result).len()==l)]
   |                                      ^
```

But `README.md` says that pearlite supports let bindings.

**Comment by jhjourdan** [comment]
The syntax is shared with Rust, and `ensures` requires a Rust expression. But let bindings are part of Rust blocks. You need to add some curly braces:

```
#[ensures({let l = lmax(@l,(@s).len());  (@result).len()==l})]
```
