### ISSUE TITLE
can verify lock-free algos ?

### ISSUE THREAD

**Issue by g302ge** [xldenis/creusot#524]
These days I have wrote some lock-free data structure, unfortunately, as we know the lock-free algos is too flexable to writing simple unit tests to test. But the traditional verification tools is not sound for rust code e.g. TLA+. 
But I don't know if this project could verify my rust lock-free code in a  simple unit test ?

Maybe in the future I will implement some lock-free structure over RDMA

thx 4 ur reply !

**Comment by xldenis** [comment]
Hi, no unfortunately Creusot does not allow reasoning about lock-free algorithms, nor does it allow reasoning about fine grained concurrency more generally. 

Lock-free data structure are very challenging, your best bet would probably be to use something like Iris to model and prove your data structure.

**Comment by g302ge** [comment]
thx 4 ur reply, I think the TLA+ is a better tool to veriy my structure , I'm familer with it. thx ur reply again

**Comment by jhjourdan** [comment]
That being said, note that we do have some plans in the medium futures, to support concurrent (including lock-free) data-structures. But this is a challenging open research problem in a semi-automated verification tool, so this is not going to happen in the near future.

**Comment by g302ge** [comment]
> 

Sounds Good, in my project there are many situations to use the Lock-Free algos, I belive the medium future could help me to verify my structures
