### ISSUE TITLE
Bool operators not being translated to WhyML correctly

### ISSUE THREAD

**Issue by georgerennie** [xldenis/creusot#528]
Some operators on `bool` seem to not be handled yet, leading to panics in creusot or WhyML that Why3 cant read.
I found the following

```rust
// This gets translated to <> in WhyML which Why3 doesnt like for bools
// It seems this was sorted for == with Bool.eqb, but this hasnt been done for !=
fn func(a: bool, b: bool) -> bool { a != b }

// These all cause creusot to panic with `not implemented: unsupported binary operation: `, creusot/src/translation.rs:178:14
fn func(a: bool, b: bool) -> bool { a & b }
fn func(a: bool, b: bool) -> bool { a ^ b }
fn func(a: bool, b: bool) -> bool { a | b }
```

I expect the bitwise operations/xor are just a case of no one getting around to implementing them yet but it would be quite nice for them to be present (and at least != should be corrected really). I imagine this probably isnt too big a change to do? and if so im happy to have a go at it if pointed in the right direction

**Comment by xldenis** [comment]
The bit wise operators is fairly expected, I haven't worked to support but wise operations on integers at all. However, it would be easy to add the Boolean ones. 

The case of `!=` should indeed be fixed though.
