### ISSUE TITLE
Help understanding why example doesn't prove

### ISSUE THREAD

**Issue by georgerennie** [xldenis/creusot#530]
Hey! I've been having a play with creusot recently and enjoying things, but I have found the example below where the postcondition on `f` doesn't prove, whereas instinctively it feels like it should as it is stating the same thing as the precondition, just inlined. Do you have any suggestions on how I could strengthen things to get this to prove?

```rust
struct Inner(Vec<bool>);
struct Outer(Vec<Inner>);

impl Inner {
	#[predicate]
	fn has_true(self) -> bool {
		pearlite! { exists<i : Int> 0 <= i && i < (@self.0).len() && (@self.0)[i] }
	}
}

impl Outer {
	#[requires(
		forall<i: Int> 0 <= i && i < (@self.0).len() ==>
			(@self.0)[i].has_true()
	)]
	#[ensures(
		forall<i: Int> 0 <= i && i < (@self.0).len() ==>
			exists<j: Int> 0 <= j && j < (@(@self.0)[i].0).len() &&
				(@(@self.0)[i].0)[j]
	)]
	fn f(&self) {}
}
```

**Comment by xldenis** [comment]
At first glance it looks totally probable like you said, however it depends on how you went about doing the proof. 

- what provers do you have installed?
- what strategy did you use to prove this?
- what happens if you run `inline_goal` first?

**Comment by suhr** [comment]
An universal suggestion: look at Why3 proof goal. It's easier to figure out from there what's missing.

Why3 has built in tactics and allow to invoke a proof assistant, so you can figure out whether it's a problem with an SMT solver or something else.

**Comment by georgerennie** [comment]
Thanks for the help both. Yes you are right I had just been running auto 3 and inline_goal/manually using alt ergo solved it quickly. This is a case of me not thinking and being too used to push button (finite state) model checking tools that give me a proof or a clear CEX where I don't normally have to think about manually invoking proof tactics.

**Comment by xldenis** [comment]
Integrating counter examples is definitely something I would like to work on in the future, but sadly does not work for now.
