### ISSUE TITLE
Review resolution machinery

### ISSUE THREAD

**Issue by xldenis** [xldenis/creusot#541]
I think it would be important to go over the machinery for resolution and clean it up / simplify it. As it stands we need a `BorrowSet` to provide information pertaining to `two_phase_borrows` but this is onerous and limiting. If we could get rid of that then we could solve #358 and also generally simplify things.

**Comment by xldenis** [comment]
I think @voidc's work counts a solid pass there already. I'll defer to him if he thinks we should close it.

**Comment by jhjourdan** [comment]
I think this is obsolete since @voidc's work.
