### ISSUE TITLE
`ide` is not a why3 command

### ISSUE THREAD

**Issue by zpzigi754** [xldenis/creusot#543]
If I execute `./ide creusot/tests/should_succeed/vector/01.mlcfg`, I get the following error message.
```
'ide' is not a Why3 command.

Available commands:
  config
  doc
  execute
...
```

If I execute `why3 -L ./prelude prove -P z3 creusot/tests/should_succeed/vector/01.mlcfg` instead, it seems to succeed with the following message.
```
Goal all_zero'vc.
Prover result is: Valid (0.03s, 100203 steps).
```

Is there any reason that `ide` is given as an input to why3?

**Comment by gmorenz** [comment]
Someone more familiar with `why` will probably come along shortly, but `ide` an an argument for `why3` for me. I'm guessing you're missing `why3-ide`.

Did you run `opam install lablgtk3 lablgtk3-sourceview3 ocamlgraph why3 why3-ide` as requested in the readme? Particularly including that last `why3-ide` which in the readme's version wraps to the next line (at least for me).

**Comment by zpzigi754** [comment]
Thank you a lot for your help! `why3-ide` was missing, because some dependency (`libgtksourceview-3.0-dev`) had not been met. After installing `why3-ide`, I could successfully run the ide command.
