### ISSUE TITLE
Why3 "syntax error" due to misplaced `pure`

### ISSUE THREAD

**Issue by gmorenz** [xldenis/creusot#564]
The placement of `pure { ... }` seems to be wrong, resulting in why3 returning "syntax error".

Here are two reproductions (I'm guessing that these have the same root cause):

```rust
#[allow(unused_imports)]
use creusot_contracts::{requires, pearlite, logic};

#[logic]
#[requires(invariants())]
fn step_logical() -> bool {
    pearlite! {
        (1i32 == 1i32) ==> true
        // Results in
        // pure {(1 : int32) = (1 : int32)} -> true
        // Should be
        // pure {(1 : int32) = (1 : int32) -> true}

        // Similar, but with two pures instead of a misplaced pure.
        // Which also results in syntax_error.
        // (1i32 == 1i32) == true
        // Resutls in
        // pure {pure {(1 : int32) = (1 : int32)} = true}
        // Should be
        // pure { (1 : int32) = (1 : int32) = true}
    }
}

#[logic]
fn invariants() -> bool {
    true
}

fn main() {}
```

Context from which the why3 snippets above are taken

```whyml
module Testbin_StepLogical_Impl
  use mach.int.Int
  use mach.int.Int32
  clone Testbin_Invariants as Invariants0
  let rec ghost function step_logical (_ : ()) : bool
    requires {[#"../src/main.rs" 5 11 5 23] Invariants0.invariants ()}

   = [@vc:do_not_keep_trace] [@vc:sp]
    [#"../src/main.rs" 7 4 17 5] pure {(1 : int32) = (1 : int32) -> true}
end
```

**Comment by xldenis** [comment]
```rust
        // Similar, but with two pures instead of a misplaced pure.
        // Which also results in syntax_error.
        // (1i32 == 1i32) == true
        // Resutls in
        // pure {pure {(1 : int32) = (1 : int32)} = true}
        // Should be
        // pure { (1 : int32) = (1 : int32) = true}
```

That's a clear bug, but I'm confused about why why3 would reject the first case? I hate this whole `pure` hack which is undocumented in why3 as well... Either don't have polymorphic `=` or just do it everywhere, none of this coercion in logic and overloading in programs stuff.

**Comment by xldenis** [comment]
Ah! it's because it's in a `let ghost function` in which `->` is not valid syntax. The existing check needs to be expanded to force a `pure` aroudn `->`

**Comment by gmorenz** [comment]
Ok, so I admit I'm confused about the why3 syntax here. But I *think* from reviewing the grammar reference that it's expecting an `expr`, and that `->` is only allowed in terms. That's assuming that `pure { block }` is an expr that parses `block` as a `term`.

**Comment by xldenis** [comment]
yep! that's exactly it. https://github.com/xldenis/creusot/blob/master/creusot/src/translation/specification/lower.rs#L237-L239 needs to be adjusted to behave like `exists` / `forall`
