### ISSUE TITLE
Mention in the readme what is the paper to cite this tool

### ISSUE THREAD

**Issue by m-fleury** [xldenis/creusot#580]
It would be cool to know what to cite exactly when referencing Creusot and mention it directly in the readme. By looking at the papers from Architecture.md, I assume it is https://hal.inria.fr/hal-03526634, but I also can be wrong.

**Comment by xldenis** [comment]
Hi Mathias,

Very good point. I would actually cite https://hal.inria.fr/hal-03737878, our ICFEM paper on Creusot.

**Comment by xldenis** [comment]
Updated the README.
