### ISSUE TITLE
creusot/tests/should_succeed/closures/06_fn_specs.rs should pass without Spec

### ISSUE THREAD

**Issue by jhjourdan** [xldenis/creusot#604]
Let's take the test 06_fn_specs.rs:

```rust
#[requires(f.precondition(a))]
#[ensures(f.postcondition(a, result))]
pub fn weaken<A, F: FnSpec<A> + Resolve>(f: F, a: A) -> F::Output {
    weaken_2(f, a)
}

#[requires(f.precondition(a))]
#[ensures(exists<f2: &mut F> *f2 == f && f2.postcondition_mut(a, result) && (^f2).resolve())]
fn weaken_2<A, F: FnMutSpec<A> + Resolve>(f: F, a: A) -> F::Output {
    weaken_3(f, a)
}

#[requires(f.precondition(a))]
#[ensures(f.postcondition_once(a, result))]
fn weaken_3<A, F: FnOnceSpec<A> + Resolve>(f: F, a: A) -> F::Output {
    FnOnce::call_once(f, a)
}
```

It should pass when replacing FnxxxSpec by Fnxxx.

**Comment by xldenis** [comment]
Yea all the spec traits should be removable.

**Comment by xldenis** [comment]
That's what I mean, the bounds should only say `Fn` and not `FnSpec`.

**Comment by jhjourdan** [comment]
Alright, the actual problem is that the default instances of FnxxxSpec do not give specs for their laws:

```rust

impl<Args, F: Fn<Args>> FnSpec<Args> for F {
    #[predicate]
    #[trusted]
    #[rustc_diagnostic_item = "fn_impl_postcond"]
    fn postcondition(&self, _: Args, _: Self::Output) -> bool {
        absurd
    }

    #[law]
    fn fn_mut(&mut self, _: Args, _: Self::Output) {}

    #[law]
    fn fn_once(self, _: Args, _: Self::Output) {}
}
```

So now the actual question is: why did not we see this before? The spec in these instances are not refinements of the trait spec, so we should not be able to write them. Of course, the problem here is that we do not check refinementsin the std lib.

**Comment by xldenis** [comment]
> Of course, the problem here is that we do not check refinementsin the std lib.

https://github.com/xldenis/creusot/issues/368

**Comment by jhjourdan** [comment]
Ok, then closing.
