### ISSUE TITLE
Add `#[modeled_by=X]` attribute

### ISSUE THREAD

**Issue by xldenis** [xldenis/creusot#63]
When using 'unsafe types' we want to give them a model, or _representation value_ in the formalization which will be used during proofs. 

The way I'm proposing to do this at the moment is to add an attribute which can be attached to type declarations which specifies which type models a given type. This does not create new verification conditions, and is meant to be used only in cases where we have separately proved the model in RustHornBelt or some other mechanism. Additionally, it should be subsumed by a proper ghost field & type invariant system (once we figure out how that works). 

What does this attribute do? Well,...

```rust
#[model=List<T>]
struct Vec<T> { 
  spooky_pointers: *mut T
}
```

Simply generates an opaque predicate `model` on Vec:

```rust
struct Vec<T> { ... }

impl Vec<T> {
  predicate! { fn model(self) -> List<T>; }
}
```

This allows us to refer to the model of a vector in contracts like so:

```rust

impl Vec<T> {
  #[ensures(^self.model() = *.self.model().snoc(e))]
   fn push(&mut self, e: T) -> { ... } 
  ...
}
```

**Comment by xldenis** [comment]
I believe that this can simply be a design pattern if we have a `#[trusted]` attribute. if we mark a predicate as `#[trusted]` it would generate an opaque predicate in why3 which is exactly what we want here.

**Comment by shiatsumat** [comment]
How is this going?

**Comment by xldenis** [comment]
I think the approach I've settled on for now is to do this through a design pattern instead. ie:

```rust
impl Vec<T> {
  #[trusted]
  logic! { fn model(self) -> Seq<T> { panic!() } }
}
```

**Comment by shiatsumat** [comment]
Yeah, the `model` function workaround perfectly works, but I was wondering if adding `modeled_by` is doable.
We prefer to use Creusot's actual specs for the paper, and it's great if the specs are free of the `.model()` parts.

**Comment by xldenis** [comment]
Perhaps, I'm just worried that it would be ad-hoc. Let's discuss this on Friday, I think jh had a related concern

**Comment by xldenis** [comment]
Yes I understand, I agree with that approach as its more lightweight than something like `modeled_by` which would require _deep_ integration into creusot. The advantage of this is that we only need to adjust the `pearlite_syn` parser to do some rewriting for us.
