### ISSUE TITLE
Spec for Result

### ISSUE THREAD

**Issue by jhaye** [xldenis/creusot#648]
`Result` is a very common type used all over the Rust ecosystem. You can largely work around the missing spec as it is right now, but just being able to call `is_some()` would be very convenient.

I'm aware of #515, but that seems to be stale.

**Comment by xldenis** [comment]
If you want to take over that PR or prepare an alternate I'd be happy to merge.

**Comment by jhaye** [comment]
It's not super pressing yet but I would probably get to it sometimes soon. Just tell me, what did you mean by "prove their specs on a re-implementation"?
Does that mean instead of using `extern_spec!{}`, just copying the original source code and annotating it?

**Comment by xldenis** [comment]
It means doing both, by making a copy of the implementations it helps ensure you didn't make a mistake in your specs.
