### ISSUE TITLE
`#![no_std]` support

### ISSUE THREAD

**Issue by CharlyCst** [xldenis/creusot#653]
Hi,

I'm investigating tools for verifying a security monitor written in Rust, I just stumbled upon Creusot and I'm trying to tinker a bit with it to see if it might be a good fit.

One of my requirements is to run in `#![no_std]` environments, I just tried to add `#![no_std]` in the `sum_first_in` exercise and it seems like this is not yet supported:

```
called impure program function in logical context "core::ops::Div::div"
 --> src/lib.rs:9:1
  |
9 | #[ensures(@result == @n * (@n + 1) / 2)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I'm not yet familiar with the code base, but I assume you are providing specifications for operations of the `std` ([here](https://github.com/xldenis/creusot/tree/master/creusot-contracts/src/std) I assume), how hard would it be to port this to `core`?
A work around for my use case would be to verify my monitor against `std`, but I would like to keep differences between verification and compiled code minimal.

As an aside, do you know about any work on verifying low-level code with Creusot? Do you think there might be other roadblocks?

Thanks!

**Comment by xldenis** [comment]
Oh hmm, that's an interesting challenge! Creusot should be compatible with `no_std` modulo implementation bugs. 

The bug here seems to be that the way specs are encoded apparently breaks in `no_std`. I don't see why that should be fundamental though, it would take a little investigation to figure out why it even occurs though.

> As an aside, do you know about any work on verifying low-level code with Creusot? Do you think there might be other roadblocks?

Depends what's meant by low-level. If it means `unsafe` code then that's not possible, additionally bitwise operations are currently unimplemented, but there's nothing fundamental there.

**Comment by xldenis** [comment]
There's [CreuSAT](https://github.com/sarsko/CreuSAT) which is probably the largest verified rust program out there. 

However, I must ask, *what* are you trying to verify, what properties do you want to establish and what cost (implementation wise) are you willing to pay for them?

**Comment by CharlyCst** [comment]
Thanks for your answer!

To elaborate a bit, I have a security monitor that manages access to ranges of physical memory. The monitor itself is composed of three layers:

1. The "syscall" dispatcher
2. The "syscall" handler
3. The memory protection backend

Layers (1) and (3) are architecture dependent, require unsafe code, and may vary in complexity (e.g. the backend manipulates page tables on `x86`, but simply update registers on `risc-v`), which makes hard to apply most verification frameworks I came across and the effort would have to be duplicated.
The handler (2), however, is (safe) Rust code that is completely architecture independent. The interface and its implementation are on purpose very simple, mostly checks, updating a few structs, and  sometimes interacting with a free list.

As a first step I would like to verify safety properties, e.g. when one domain grants a region of physical memory to another then the changes are properly reflected in the data structures. This would only interact with layer (2) and therefore standard safe (but `no_std`) Rust code.

Regarding implementation cost, I'm trying to keep it minimal. Unfortunately there is no silver bullet for software verification yet, so part of my current investigation is to determine what are the cost of the different frameworks. I'm also paying attention to [serval](https://dl.acm.org/doi/pdf/10.1145/3341301.3359641) for its high degree of automation (at the cost of restriction on the implementation).

**Comment by xldenis** [comment]
> As a first step I would like to verify safety properties, e.g. when one domain grants a region of physical memory to another then the changes are properly reflected in the data structures. This would only interact with layer (2) and therefore standard safe (but no_std) Rust code.

At a high-level, this seems like the kind thing Creusot could handle, though of course the details are what matters.

> Regarding implementation cost, I'm trying to keep it minimal. 

With creusot you don't have to sacrifice performance, at least that hasn't been our experience so far, but some ways of writing code are easier to prove than others, and that must be taken into account. The implementation cost I was referring to was actually more about the specifications and proof complexity.

**Comment by xldenis** [comment]
I have a fix for the original issue posted here, I don't know why I didn't just fix it originally.. However, I don't have any significant `no_std` code to test if there are further issues.
