### ISSUE TITLE
Overflows are not checked inside Pearlite

### ISSUE THREAD

**Issue by safinaskar** [xldenis/creusot#655]
Consider this code:
```rust
fn f(a: i32) {
    #[invariant(a, a + 1i32 == a + 1i32)]
    for i in 0..5 {
    }
}
```

It is reported as valid, but this is wrong, because addition in invariant may overflow. I use master ( 8342c2caa5be71991145aca9b1eee4f0ea1676ff )

**Comment by xldenis** [comment]
Creusot logic is total, and does not have overflow, but moreover Creusot doesn't actually have arithmetic operations on machine integers in the logic yet, only on mathematical ones.

We are planning on adding machine arithmetic in the logic but even then you won't get an overflow. What you will get is an unspecified value if you do `MAX + 1`. You'll still be able to prove reflexivity of that value but that's about it.

**Comment by xldenis** [comment]
Also see #654

**Comment by xldenis** [comment]
I'm closing as wontfix, because we aren't likely to check overflows in logical expressions anytime soon. However, #654 is related to this and still needs to be addressed, and we need to add machine arithmetic in the logic too.
