### ISSUE TITLE
Installation instructions do not work

### ISSUE THREAD

**Issue by Timmmm** [xldenis/creusot#662]
```
> git clone https://github.com/xldenis/creusot.git
Cloning into 'creusot'...
remote: Enumerating objects: 26080, done.
remote: Counting objects: 100% (26080/26080), done.
remote: Compressing objects: 100% (8168/8168), done.
remote: Total 26080 (delta 17714), reused 25820 (delta 17654), pack-reused 0
Receiving objects: 100% (26080/26080), 14.75 MiB | 12.61 MiB/s, done.
Resolving deltas: 100% (17714/17714), done.

> cargo install --path creusot
error: found a virtual manifest at `D:\workspace\creusot\Cargo.toml` instead of a package manifest
```

**Comment by xldenis** [comment]
You need to enter the `creusot` directory

**Comment by Timmmm** [comment]
Ah thanks. Unfortunately then I get another error:

```
> cargo install --path creusot
error: invalid toolchain name: 'ci/rust-toolchain'
```

**Comment by xldenis** [comment]
oh right, windows doesn't have symlinks. For now, I suppose you can just copy the file out of the `ci` directory. I'll try to figure out how to fix that.

**Comment by Timmmm** [comment]
Ah right. Took me a while to figure out since Git creates a file for the symlink but it just contains the target path (i.e. `ci/rust-toolchain`.

For anyone else following along, overwrite that file with the one from `ci/rust-toolchain`.

If it were me I would just create two copies of the file in the repo. It's like 3 lines. Maybe put a comment at the top so people remember to update both or even a check in CI. Symlinks were a mistake. Best to avoid them if at all possible.

Maybe worth setting up a Windows CI builder too?

In any case, after doing that it compiled fine, thanks!
