### ISSUE TITLE
Failed to prove a simple postcondition

### ISSUE THREAD

**Issue by kazkob** [xldenis/creusot#680]
```rust
use creusot_contracts::*;

#[ensures (@^n == 0)] // fails to prove the postcondition
fn failing(n: &mut usize) {
    while false {
        *n = 0;
    }
    *n = 0;
    proof_assert!(@n == 0); // this succeeds
}
```

The above example seems to have no problem, but the proof of the postcondition fails even though the last proof assertion is proved.

I'm using why3 with commit 382d5dcf (the master as of Feb 1), and creusot with commit 2b579cab.

**Comment by kazkob** [comment]
Sorry, I now realize this can be avoided by adding a "proph_const" invariant

**Comment by xldenis** [comment]
> Sorry, I now realize this can be avoided by adding a "proph_const" invariant

I am crossing my fingers that this will be fixed this week due to a change in Why3!

**Comment by xldenis** [comment]
If you update `why3` and `creusot` this issue is now fixed!
