### ISSUE TITLE
Using `ghost!` produces an invalid mlcfg

### ISSUE THREAD

**Issue by utaal** [xldenis/creusot#682]
```rust
use creusot_contracts::*;

#[requires(*a <= u64::MAX / 2u64)]
#[ensures(^a > *a)]
fn add_some(a: &mut u64) {
    *a += 1;
}

#[requires(*a == 3u64)]
#[ensures(^a > *a)]
pub fn foo(a: &mut u64) {
    let a_p: Ghost<u64> = ghost!(*a);
    add_some(a);
    assert!(*a > *a_p);
}
```

results in "../creusot-bin.mlcfg", line 83, characters 40-41: unbound type symbol 't'

Mlcfg (paths redacted): https://gist.github.com/utaal/2dcaf23b35a54c5ef3ffb6cbb603bff6

**Comment by xldenis** [comment]
Oh wow, that is a *unique* bug, huh, seems to be related to the special treatment deref gets for ghost though I'm unsure why it hasn't manifested before!
