### ISSUE TITLE
Unhygienic temporary variable in invariant macro

### ISSUE THREAD

**Issue by kazkob** [xldenis/creusot#685]
https://github.com/xldenis/creusot/blob/7520fe700ad3c992aeac873ff60321022d7ddf7c/creusot-contracts-proc/src/invariant.rs#L156

It seems `i` is intended to be hygienic here, but it's not in translated code.
```
pub fn ng1() {
    let i : u8 = 100;

    #[invariant(inv, true)]
    for j in 0usize..1 {
        proof_assert!(i == 100u8); // results in ill-typed mlcfg
    }
}

pub fn ng2() {
    let i : usize = 100;

    #[invariant(inv, true)]
    for j in 0usize..1 {
        proof_assert!(i == j); // provable
    }
}
```

**Comment by xldenis** [comment]
Thanks! Indeed since we only use it to bind the for-loop pattern, it should be made hygenic. I'll fix that right now.

**Comment by xldenis** [comment]
It's been a while, but should `def_site` be exactly the right hygiene? 

> A span that resolves at the macro definition site.

Perhaps instead its the body that's being mistreated?

**Comment by xldenis** [comment]
Ok I think I've isolated the cause, and it's not actually the macro, it's because of the way a substitution is constructed for `proof_assert` which seems to not properly account for something hygiene related.

**Comment by xldenis** [comment]
I've renamed this temporary variable to avoid clashes.
