### ISSUE TITLE
Can't prove the resolve of an FnOnce in a branch

### ISSUE THREAD

**Issue by boulme** [xldenis/creusot#699]
From discussion #698, I would expect this code to be provable:

```#![cfg_attr(not(feature = "contracts"), feature(stmt_expr_attributes, proc_macro_hygiene))]
use creusot_contracts::*;

#[requires(run.precondition(()))]
#[ensures(
    (b && run.postcondition_once((),()))
        || (!b && run.resolve()))]
fn test<F:FnOnce() -> ()>(b: bool, run: F) {
    if b { run() }; 
}

#[ensures((n > 7u32 && result == 2u32) || (n <= 7u32 && result == 0u32))]
fn example(n: u32) -> u32 {
    let mut r = 0u32;
    let run =
        #[ensures (r == 2u32)]
        || { r = 2 };
    test(n > 7, run);
    r
}
    
fn main(){
    example(8);
}
```
But, currently (e.g. from 0ffd39ad), the postcondition of `test` cannot be proved.

**Comment by xldenis** [comment]
I investigated this a bit yesterday. I'm still uncertain _why_ this happens, but the rustc liveness analysis insists that the closure is live all the way through to the return. This occurs for all variables of generic (potentially `Drop`) types. Some further investigation is still required to elucidate this behavior.

**Comment by boulme** [comment]
I am not sure that this will really help you...  But yes, I agree that drop is expected to be invoked in both branches. For example, consider the following variant:
```
#[derive(Debug)]
struct Toto { x: u32 }

impl Drop for Toto {
    fn drop(&mut self) {
        dbg!(self);
    }
}

fn incr(mut r: Toto) {
    r.x += 3;
}

fn test<F:FnOnce() -> ()>(b: bool, run: F) {
    if b { run() }; 
}

fn example(n: u32) -> () {
    let r = Toto { x: 0u32};
    test(n > 7, || { incr(r) });
}
    
fn main(){
    example(8);
    example(7);
}
```
If I quickly look at the MIR code generated by `rustc --emit mir`, I see that in the branch not containing the call, the `drop` function is explicitly called. In contrast, the branch containing `call_once` does not explicitly invoke `drop`, because `drop` is expected to be invoked by `call_once` itself. This is the only difference I see between the two branches.

I have also verified that the MIR generated (by `rustc --emit mir`) for `test` in the original example is the same as in this last one. 

Good luck!
