### ISSUE TITLE
Add no overflow-check mode

### ISSUE THREAD

**Issue by shiatsumat** [xldenis/creusot#70]
For some verification problems, we want to give up overflow checks, especially when verification is already interesting without overflow checks and we need currently unsupported features of Creusot for proving that overflow does not happen.

So in order to add many benchmarks, we need no overflow-check mode.
In this mode, probably we just have to use `Int` instead of `Int32`, `Uint32`, etc. for modeling Rust's bounded integer types.

**Comment by xldenis** [comment]
Yea, I fully agree, this would be a big feature for when you're just iterating on the core part of a proof. Integers are a PAIN! to deal with.

I don't think it would be too complex to implement:

1. Add a flag to `Options` in https://github.com/xldenis/creusot/blob/master/creusot/src/options.rs
2. Make `intty_to_ty` read that flag during translation. https://github.com/xldenis/creusot/blob/master/creusot/src/translation/ty.rs#L247

**Comment by xldenis** [comment]
Everything else should "just work"

**Comment by xldenis** [comment]
A third step would be to add a some annotation that the test runner can use to enable this option, like how `WHY3SKIP` works to skip why3 verification of output.
