### ISSUE TITLE
unable to start prove one example from tests and CreuSAT (Friday and also another example)

### ISSUE THREAD

**Issue by andreykl** [xldenis/creusot#704]
Hello!

First of all, this is a quite exciting thing in my opinion!

I have some troubles when trying start using Creusot.
What i'm doing is 
* I'm going through README.md: clone and build Creusot, this work ok (I also tryed to run creusot tests with `cargo test`, no errors). So, just to make sure I explained it in right way: it looks like `cargo install --path creusot` worked fine.
* Now I do `cargo new test_creusot` 
  * then add 
```
[dependencies]
creusot-contracts = { path = "/path/to/creusot/creusot-contracts" }

[features]
contracts = ["creusot-contracts/contracts"]
```
to test_creusot/Cargo.toml, then
  * `rm test_creusot/src/main.rs` 
  * `cp /path/to/creusot/creusot/test/should_succeed/vector/01.rs test_creusot/src/lib.rs`
  * also copying `rust-toolchain` from `creusot/ci` to `test_creusot`
  *  `cd test_creusot` and ` cargo creusot`, the result is

```
$ cargo creusot
   Compiling pearlite-syn v0.2.0 (/home/andrey/creusot/creusot/pearlite-syn)
   Compiling creusot-contracts-dummy v0.2.0 (/home/andrey/creusot/creusot/creusot-contracts-dummy)
   Compiling creusot-contracts-proc v0.2.0 (/home/andrey/creusot/creusot/creusot-contracts-proc)
    Checking creusot-contracts v0.2.0 (/home/andrey/creusot/creusot/creusot-contracts)
error[E0636]: the feature `rustc_attrs` has already been declared
 --> <crate attribute>:1:9
  |
1 | feature(rustc_attrs)
  |         ^^^^^^^^^^^

warning: calling an external function with no contract will yield an impossible precondition
  --> /home/andrey/creusot/creusot/creusot-contracts/src/std/iter/map_inv.rs:87:15
   |
87 |         match self.iter.next() {
   |               ^^^^^^^^^^^^^^^^

warning: load the `creusot_contract` crate to enable resolution of mutable borrows.

warning: calling an external function with no contract will yield an impossible precondition
  --> /home/andrey/creusot/creusot/creusot-contracts/src/std/iter/map_inv.rs:93:30
   |
93 |                 let r = Some((self.func)(v, ghost! { self.produced.inner() })); // FIXME: Ghost should be Copy
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0636`.
warning: `creusot-contracts` (lib) generated 3 warnings
error: could not compile `creusot-contracts` due to previous error; 3 warnings emitted

```

I recieved the same answer when tryed to go through CreuSAT instructions and entered `cargo make prove-Friday`

I'm not sure what i'm doing wrong. I'm also a bit newbe in Rust, so, it is possible this is some kind of naive error.

**Comment by xldenis** [comment]
Hi @andreykl, thanks for opening the issue, this is an unfortunate wart in the creusot ux. you need to pass the `--feature=contracts` flag for it to work properly. I'm hoping to fix this in the near future though. 

For creuSAT, @sarsko  set up a series of `cargo make` tasks so if you `cargo install cargo-make` you can then just do `cargo make prove-Friday` (other commands are listed in his readme).

**Comment by andreykl** [comment]
Ah! `cargo creusot -- --features=contracts` works fine in the `CreuSAT/Friday` folder now. I can move forward, thank you!
