### ISSUE TITLE
const definitions are not allowed in impl blocks

### ISSUE THREAD

**Issue by jhjourdan** [xldenis/creusot#749]
There is no reason to allow them globally but not in impl blocks.

**Comment by xldenis** [comment]
? are you saying we shouldn't allow them globally but should allow them in impls? Or that we should allow them everywhere?

**Comment by jhjourdan** [comment]
I think they should be allowed everywhere, and that I don't see why it would be more complicated to accept them (in non-trait-instantiation) impl blocks. So I consider this a s "bug" (or lack of an expected feature) if this is not possible.

**Comment by xldenis** [comment]
Indeed, but `const` blocks are handled in a special way which breaks compilation in Creusot. I believe @voidc had sketched a solution at some point.

**Comment by voidc** [comment]
Closed by #765.
