### ISSUE TITLE
Creusot should detect old & incompatible versions of why3

### ISSUE THREAD

**Issue by xldenis** [xldenis/creusot#758]
We make frequent and fast moving changes in Why3 for Creusot, but this is a problem as why3 is only infrequently released and if you forget to `pin` and `opam upgrade` why3, you'll get cryptic errors. 

I was thinking that `cargo creusot` could attempt to parse the version string of the `why3` binary and warn / error if the user is using an old version.

**Comment by voidc** [comment]
Closed by #762
