### ISSUE TITLE
Annotating a function with `predicate` which does not return `bool` results in a Why3 syntax error

### ISSUE THREAD

**Issue by sarsko** [xldenis/creusot#777]
Ie:
```rust
#[predicate]
fn my_pred() -> Int {
    0
}
```
gives:
` characters 45-46: Type mismatch between int and bool`
in Why3 IDE

**Comment by xldenis** [comment]
Huh... I thought I had fixed that recently. Are you on latest master?

**Comment by sarsko** [comment]
Oh, my bad, seems like this was fixed in https://github.com/xldenis/creusot/commit/60ed3f45b563c6290878c76974f92e5cf85c2c5a, and I'm on 5cc6cdd. My bad.
