### ISSUE TITLE
Why3 IDE mlcfg error on small floats.

### ISSUE THREAD

**Issue by sarsko** [xldenis/creusot#791]
Ie:
```rust
fn i_love_floats() {
    let _ = 0.000001;
}
```
Causes the following error in Why3 IDE:
`File "../Scratch.mlcfg", line 3363, characters 10-121: Invalid floating point literal: '0.0000009999999999999999547481118258862586856139387236908078193665'`

**Comment by xldenis** [comment]
......

**Comment by jhjourdan** [comment]
We should us hexadecimal float literals, which are supported by Why3 (but maybe a bit difficult to pretty-print in Rust).

**Comment by xldenis** [comment]
Yea, I'm having issues finding a simple way to print decimal floats such that the outputs are all representable. Simply increasing the precision of the printing doesn't work?

**Comment by xldenis** [comment]
I actually didn't find a library to print floats as hex in Rust, but I was able to use the `integer_decode` function to then cobble together this functionality. Given that there is no rounding involved (just interpreting byte patterns as different bases of numbers), I don't expect any further issues.
