### ISSUE TITLE
Help with Creusot's Macros

### ISSUE THREAD

**Issue by Drodt** [xldenis/creusot#827]
I want to understand Creusot's internals a bit better but I am a bit confused by the use of the attribute macros in `creusot-contracts`, `creusot-contracts-proc`, and `creusot-contracts-dummy`.

It seems that when `--cfg creusot` is set, e.g., by `cargo-creusot`, the `creusot-contracts-proc` are used to insert attributes and Creusot items. When it is not set, the dummy contracts are called and do nothing.

So two questions:

1. Why does this work? When I try to replicate it with my own crates, the `--cfg creusot` flag is not passed to the other crates. The dummy macros are always chosen.
2. When I expand with rustc (`cargo rustc --profile=check -- -Zunpretty=expanded`) the expanded code always has the creusot attributes and items, although I did not add `--cfg creusot`. Why?

If this is not the correct place for these questions, let me know!

**Comment by xldenis** [comment]
> Why does this work? When I try to replicate it with my own crates, the --cfg creusot flag is not passed to the other crates. The dummy macros are always chosen.

Can you show exactly how you tried to pass the cfg flag? `cfg` flags are global so they should affect all dependencies as well.

**Comment by Drodt** [comment]
Thanks for the quick response!

> Can you show exactly how you tried to pass the cfg flag? `cfg` flags are global so they should affect all dependencies as well.

For example `cargo rustc -p rml-example --profile=check -- -Zunpretty=expanded --cfg rml` with my own project, where `rml` is the equivalent to `creusot`.

> Hrm, this might have to do with cargo caching? Was the previous build using the macros or the dummies?

The last build would have been without the feature. I did not think of the cache! So I have to clean after each build, then?

**Comment by Drodt** [comment]
In that case, I get:
```
error: unexpected argument '--cfg' found

  tip: to pass '--cfg' as a value, use '-- --cfg'

Usage: cargo rustc [OPTIONS] [args]...

For more information, try '--help'.
```

**Comment by xldenis** [comment]
Perhaps you need to feed it like this `cargo --cfg rustc ...` what's clear however is that everything after -- is exclusively a rustc argument but you actually need to tell cargo to turn on this cfg. Really I think that trying to work with cargo rustc is going to be more trouble than it's worth here

**Comment by Drodt** [comment]
I didn't really want to work with cargo rustc but with rustc itself. I just assumed wrongly that cargo would be a more lightweight wrapper around rustc than it is. I thought I could test the output with this command.

Cargo seems to first compile the crates and then call rustc. This messes with the --cfg argument.

Anyway, I think I understand now. Thank you for your time!
