### ISSUE TITLE
Spec `split_first_mut` is wrong

### ISSUE THREAD

**Issue by xldenis** [xldenis/creusot#833]
It uses a conjunction instead of an implication, and in fact should be updated to a match anyways. Fixing the spec breaks the `take_first_mut` test.

**Comment by jhjourdan** [comment]
It is easy to fix the spec of `split_first_mut`, but fixing the test requires extentionality of the slice type, which in turns depends on this Why3 issue: https://gitlab.inria.fr/why3/why3/-/issues/287

In between, I will just add an extentionality axiom by hand.
