### ISSUE TITLE
`cargo creusot` results in `Library not loaded` error

### ISSUE THREAD

**Issue by adpaco-aws** [xldenis/creusot#882]
Running `cargo creusot` on an example that doesn't use the `rust-toolchain` file from this repository results in the error:

```
dyld[30463]: Library not loaded: @rpath/librustc_driver-f54dda96e19abd8e.dylib
  Referenced from: <FE780130-DD94-307D-A29A-ED5E0A1AFF44> /Users/username/.cargo/bin/cargo-creusot
  Reason: tried: '/Users/username/.rustup/toolchains/stable-x86_64-apple-darwin/lib/librustc_driver-f54dda96e19abd8e.dylib' (no such file), '/Users/username/lib/librustc_driver-f54dda96e19abd8e.dylib' (no such file), '/usr/local/lib/librustc_driver-f54dda96e19abd8e.dylib' (no such file), '/usr/lib/librustc_driver-f54dda96e19abd8e.dylib' (no such file, not in dyld cache)
zsh: abort      cargo creusot
```

While the step of copying the rust-toolchain file is [mentioned in the README](https://github.com/xldenis/creusot#verifying-with-creusot-and-why3), it's an easy-to-miss step and the error doesn't indicate what you need in order to fix it.

`cargo creusot` can be changed so it does this for you, but I believe there are some corner cases to consider then (e.g., what if the target project has its own `rust-toolchain` file?). At the very least, it can be changed so the error is nicer.

**Comment by xldenis** [comment]
Fixed!
