### ISSUE TITLE
Evaluate Profile-Guided Optimization (PGO) and LLVM BOLT

### ISSUE THREAD

**Issue by zamazan4ik** [xldenis/creusot#884]
Hi!

Recently I checked Profile-Guided Optimization (PGO) improvements on multiple projects. The results are [here](https://github.com/zamazan4ik/awesome-pgo/). LLVM-related results are [here](https://github.com/llvm/llvm-project/issues/63486). According to the tests, PGO usually helps with the compiler and compiler-like workloads (like static analysis). That's why I think trying to optimize Creusot with PGO can be a good idea.

I can suggest the following action points:
* Perform PGO benchmarks on Creusot. And if it shows improvements - add a note about possible improvements in Creusot's performance with PGO.
* Providing an easier way (e.g. a build option) to build scripts with PGO can be helpful for the end-users and maintainers since they will be able to optimize Creusot according to their own workloads.

Maybe testing Post-Link Optimization techniques (like [LLVM BOLT](https://github.com/llvm/llvm-project/blob/main/bolt/README.md)) would be interesting too but I recommend starting from the usual PGO.

For the Rust projects, I suggest PGO optimizing with [cargo-pgo](https://github.com/Kobzol/cargo-pgo).

**Comment by jhjourdan** [comment]
Performance is not (yet ?) an issue for the part of the code of Creusot written in Rust.
