### ISSUE TITLE
Invalid MLCFG outputs due to improper printing of `let ... in ...`

### ISSUE THREAD

**Issue by shiatsumat** [xldenis/creusot#92]
Currently, Creusot sometimes outputs invalid mlcfgs due to improper syntax printing of `let ... in ...`.

For example, when Creusot inputs the following Rust code,
```rust
#[ensures(^x.0 == *x.0)]
fn drop_pair(x: (&mut u32, &mut u32)) {}
```
it outputs the following MLCFG.
```ocaml
module DropPair_DropPair_Interface
  use prelude.Prelude
  use mach.int.Int
  use mach.int.UInt32
  val drop_pair (x : (borrowed uint32, borrowed uint32)) : ()
    ensures {  ^ let (_, a) = x in a =  * let (_, a) = x in a }
```
This is invalid, because the body of the first `let` has wrongly become `a =  * let (_, a) = x in a`,
while what we intend is actually `^ (let (_, a) = x in a) = * (let (_, a) = x in a)`.

As seen here, usually we should add parentheses around `let ... in ...`.

**Comment by xldenis** [comment]
I think we just need to adjust the precedence of `^` during printing.

**Comment by shiatsumat** [comment]
Thanks!

**Comment by shiatsumat** [comment]
(To make extra sure) I suppose we should also fix printing on `*` and probably other connectives as well.

**Comment by xldenis** [comment]
Yea I'm overhauling the printing's handling of precedence and associativity so we never have to deal with this in the future.
