### ISSUE TITLE
Structural `resolve` is not working

### ISSUE THREAD

**Issue by shiatsumat** [xldenis/creusot#94]
Creusot can't verify the following.
```rust
#[ensures(^ x.0 == * x.0)]
fn drop_pair(x: (&mut u32, &mut u32)) {}
```

First, currently Creusot outputs unreadable MLCFGs due to improper printing (as reported in #92).
But even after we fix the MLCFG by hand, Creusot still fails to verify this.

When we open the Why3 IDE and check the "Task" for the postcondition, we get the following.
```ocaml
--------------------------- Local Context ---------------------------
predicate resolve2 (borrowed uint32)
predicate resolve1 (borrowed uint32)
predicate resolve (self:(borrowed uint32, borrowed uint32)) =
  resolve1 match self with
  | a, _ -> a
  end && resolve2 match self with
         | _, a -> a
         end
constant x1 : borrowed uint32
constant x : borrowed uint32
constant x_11 : borrowed uint32
constant x_1 : borrowed uint32
H1 : x_11 = x1
H : x_1 = x
Assume : resolve (x_11, x_1)
------------------------------- Goal --------------------------------
goal drop_pair'vc : (^ x1) = (* x1)
```
Crucially, also we can see the definition of `resolve` on the type `(&mut u32, &mut i32)`, it calls functions `resolve1` and `resolve2` on `&mut i32`, whose definitions are opaque in this context.

I think this is a critical bug that should be fixed soon.

**Comment by xldenis** [comment]
Ruh roh! Yes this needs to be fixed ASAP. I'll look into why we don't get the instance for borrows, that's very weird.

**Comment by shiatsumat** [comment]
Great!

**Comment by xldenis** [comment]
https://github.com/rust-formal-methods/wg/issues/3 discusses the deeper fixes to `rustc` that need to occur to fully close this issue. 
However, I should be able to improve the situation in the interim but it will take a good amount of work.

**Comment by xldenis** [comment]
Closing as #101 has fixed this issue! We are free at last!
